### ISSUE TITLE
No custom fields found

### ISSUE THREAD

**Issue by yeomann** [freakdesign/shopify-custom-fields#32] opened 2016-06-03 08:43 UTC
I have created meta field under General > Store Metafields using ShopifyFD but i can't see any custom field under product. Any help would be appreciated!

**Comment by freakdesign** [comment] 2016-06-03 09:09
Hey @yeomann,

Can you post the details of the metafield you created under `/admin/settings/general`?
That will let me try and replicate the problem you might be having.

Also,
- Are you using the bookmarklet or Chrome extension?
- Do you see any errors? If so, what are they?
- When you "can't see any custom field" are you seeing any Custom Fields UI on the page?

**Comment by dexcell** [comment] 2016-06-03 12:45
Hi, i have the same issue. (First time user, so i may did something wrong)

Hello,
I even don't see anything on `/admin/settings/general`

On My product item page it's shown like this.
![screen shot 2016-06-03 at 7 38 31 pm](https://cloud.githubusercontent.com/assets/41800/15778871/35bd22c0-29c3-11e6-9a2d-d0993bb79b17.png)

So i went to another app to create metafield with `c_f` as namespace, and put some key and value to it.
![screen shot 2016-06-03 at 7 42 51 pm](https://cloud.githubusercontent.com/assets/41800/15778918/6ab5199c-29c3-11e6-959d-fdd7b7c8a46e.png)

And back to my product page, and refresh the page.
But it still says No custom fields found

**Comment by dexcell** [comment] 2016-06-03 12:50
Oh, i found the problem!

It looks like i am still using old chrome extension! (THE PINK ONE)
Sorry for the trouble. Maybe you should take the old one down from chrome appstore, since it's shown up on google search result and may lead to missunderstanding.

Thank you for the extension 👍

**Comment by freakdesign** [comment] 2016-06-03 16:42
@dexcell The pink one is **Custom Fields**. It's not an old one, though if you're comparing it to ShopifyFD it is different. [ShopifyFD](http://shopifyfd.com/) does more than than just metafield editing. Custom Fields only does metafield editing. 

There is a specific setup for Custom Fields (as noted in the help PDF) A few people miss this step, or do it incorrectly. I'll improve the docs to cover people in the short term.

### Example from one of my test stores:
General settings (`/admin/settings/general`) showing ShopifyFD
![image](https://cloud.githubusercontent.com/assets/1378665/15786002/9d6bb82a-29fd-11e6-8e6d-6f4b5efdd1ae.png)

Product page running Custom Fields:
![image](https://cloud.githubusercontent.com/assets/1378665/15786060/d9ed5e7a-29fd-11e6-89c3-de8ca86e73c6.png)

**Comment by dexcell** [comment] 2016-06-04 03:09
Thank you, amazing explanation

**Comment by yeomann** [comment] 2016-06-08 12:23
I am sorry didn't work for me i install extension through this url and also the shopifyfd extension https://chrome.google.com/webstore/detail/custom-fields-for-shopify/alfplfpobekffinigeidgmmfjollghln 
i went to settings and created meta field. check attachment ![img](http://i.imgur.com/e16GVWb.png) 
afterward i went to products and no luck. Let me know show what i see. ![productimg](http://i.imgur.com/XeJ7b7c.png)

PS: i have given up. I don't think my customer will be happy if i will hey you know what for adding additional details or something for your product, a) you gotta use Chome only b) all this complexity.

I wonder why Shopify don't allow/give such option to create something like a **advance custom field** such as you get that functionality in WordPress.

Lastly i appreciated you effort @freakdesign. Don't know why its not working for me. But i am not going to use this solution so if you had like close this issue.

**Comment by freakdesign** [comment] 2016-06-08 12:33
You have not used the namespace of `c_f` nor `custom_fields`. If you want to use a different namespace you need to set things up to work that way. Using a custom namespace is mentioned in the (small) [help PDF](https://freakdesign-us.s3.amazonaws.com/shopify/custom_fields/freakdesign-custom-fields-for-shopify-guide.pdf).

![image](https://cloud.githubusercontent.com/assets/1378665/15894350/d169eba0-2dc8-11e6-8bc3-4e2d4d9a34a9.png)

Since this is not a bug, and more a problem with setup, I'll close this issue.

**Closed by freakdesign** 2016-06-08 12:33 UTC
Labels: question
